### ISSUE TITLE
/mfm hoppers is broken?

### ISSUE THREAD

**Issue by bobhenl** [Zrips/MobFarmManager#18]
Hi, I think that /mfm hopper cmd is broken a little bit...
```
HopperControl:
  #  
  # Enables or disable hopper item transfer rate
  # Only for 1.8.x and above servers
  # By enabling this any contraptions based on regular hopper ticking will break and hopper transfer rate will be adjust dinamicaly
  # In case hopper is being used intensively, its transfer interval will get increased until max limit to lower load on server
  # It will get reseted if hopper is not used for particular time frame
  Enabled: true
  # Defines default item transfer rate in ticks (20 ticks 1 second). 8 is default vanilla behavior
  Default: 8
  # Defines max interval between item transfer. 40 will result in 1 item every 2 seconds.
  SlowestRate: 40
  # Defines how often to adjust hopper transfer rate in actual transfer. So 30 will mean that after hopper transfers 30 items, its rate will get adjusted
  AdjustEvery: 30
```
![image](https://user-images.githubusercontent.com/18662086/110020389-c6f4df80-7d29-11eb-9d42-41f142b591cd.png)
![image](https://user-images.githubusercontent.com/18662086/110020385-c65c4900-7d29-11eb-8d91-17dd52833e5a.png)
There's "NoInformation" string message....
