### ISSUE TITLE
Add function to limit player_head and player_wall_head

### ISSUE THREAD

**Issue by UnitedCraft** [Zrips/MobFarmManager#33]
Suggest adding a function to limit player_head and player_wall_head material.

**Comment by Zrips** [comment]
You can already do this by adding extra entries for block limitations, like
```
BlockTypes:
  Limit: true
  List:
    HOPPER: 10
    PISTON: 10
    STICKY_PISTON: 10
    OBSERVER: 10
    PLAYER_HEAD: 10
    PLAYER_WALL_HEAD: 10
```
