### ISSUE TITLE
[Suggestion] Add "SIGN" and "ITEM_FRAMES" in BlockTypes

### ISSUE THREAD

**Issue by NoltoxGit** [Zrips/MobFarmManager#69]
Hello,
Is it possible to add theses items in the `BlockTypes:` limite please ?

```yml
BlockTypes:
  Limit: true
  CheckPistonMove: true
  List:
    SIGN: 30 # All signs and hanging signs is counted for this limit (all types of wood)
    ITEM_FRAMES: 25 # All items frames is counted for this limit (Item frame and glow item frame)
```
