### ISSUE TITLE
RemoveExisting: true/false per entities

### ISSUE THREAD

**Issue by bobhenl** [Zrips/MobFarmManager#8]
Hi, I wanna suggest make RemoveExisting: per-entity. Because imagine, if you have 10 zombies and it's above limit and next 10 will come there, they won't be removed, and it's wrong (I have spawn check true, so it only counts if new zombie walk there).

But if player has 10 villagers and will go there with 1 new, so he will have 11, one of the old ones will despawn... So, players are complaining about despawning villagers.

Would be nice, if we can set it specifically to the:
```
EntityTypes:
  DROPPED_ITEM:
    Use: true
    Limit: -1
    # Defines limits by specific worlds
    # If world is not defined then default limit will be used
    # If world is provided then we will ignore default limit and will use provided for this specific world
    WorldLimit:
      world: -1
      world_nether: -1
      world_the_end: -1
```

Here if you add way RemoveExisting:, it would be very nice. Players stop complaining about disappearing entities.
