### ISSUE TITLE
out of memory?

### ISSUE THREAD

**Issue by siulung201314** [Zrips/MobFarmManager#91]
Core: git-Purpur-2062 (MC: 1.20.1)*
MobFarmManger: 4.7.1
CMILib: 1.5.1.3

My server has different kinds of mob farm such as zombified_piglin, hoglin and warden farm.
I have enabled the auto clear funtion to remove excess mobs every 30 second. (GroupChunks：false)
However, it causes to keep increasing the memory used on long[], java.lang.Object[], and net.minecraft.world.level.pathfinder.PathPoint.
I check the memory used by using spark heapsummary.
![image](https://github.com/user-attachments/assets/8ef63727-fefc-409c-aa1f-50b66f9d98bc)
Finally the server crashes because of out of memory after a few hours.

I have tried to disable the auto clear funtion to check if the memory used on long[], java.lang.Object[], and net.minecraft.world.level.pathfinder.PathPoint increase or not.
Finally, the memory used does not increase any more and the server does not crashes.

I am not sure if the auto claer function is related to this issue but I have tested both stituation for a day and get the result.

**Comment by Zrips** [comment]
Can you provide config file for testing? Or atleast AutoClean section from it, just to have more accurate test environment to yours

**Comment by siulung201314** [comment]
Sorry for my late reply.

It is the part of AutoClean section.
```
AutoClean:
  #  
  # Checks chunks around players for over populated farms
  Use: true
  #  
  # Informs users with mfm.cleaninform permission node how many entities we cleaned up and which ones in particular
  Inform: true
  # How often to check chunks in seconds. Minimal value: 15
  Interval: 300
  # Defines max amount of entities which we will remove from a chunk or chunk group when checking it
  # Set to 0 if you want to disable limit
  MaxRemoved: 0
  # When set to true and value for ChunkRadius is provided, we will group more then one chunk into check
  GroupChunks: false
  # Range around player in chunks to check. 2 means that 9 chunks will be checked, 3 - 25 chunks and so on
  # Max value is 5 to avoid unnecessary load on server
  # 1 = 1x1 area = 1 total chunks
  # 2 = 3x3 area = 9 total chunks
  # 3 = 5x5 area = 25 total chunks
  ChunkRadius: 1
  # Defines range from 1 to 2 in chunks we will check around player when performing autoclean
  # This only applies when you dont have GroupChunks enabled
  ExpandRange: 4
```
  
  It is the part of EntityGroups section.
  ```
EntityGroups:
  Animals:
    RemoveExisting: true
    Use: true
    Limit: 10
    List:
    - Pig
    - Cow
    - Horse
    - Rabbit
    - Sheep
    - Chicken
    - Axolotl
    - Goat
    - Bee
    - Skeleton_horse
    - Llama
    - Wolf
    - Mushroom_cow
    - Ocelot
    - Polar_bear
    - Panda
    - Cat
    - Trader_llama
    - Turtle
    - Strider
    - Mule
    - Rabbit
    - Fox
    - Parrot
    - Frog
    - Tadpole
    - Allay
    - Camel
    - Sniffer
    Worlds:
    - Survival_world
    - Survival_world_nether
    - Survival_world_the_end
    - Server_dungeon
  Monsters:
    RemoveExisting: true
    Use: true
    Limit: 10
    List:
    - Zombie
    - Skeleton
    - Slime
    - Creeper
    - Cave_spider
    - Spider
    - Enderman
    - Zombified_piglin
    - Blaze
    - Drowned
    - Endermite
    - Evoker
    - Ghast
    - Guardian
    - Hoglin
    - Husk
    - Magma_cube
    - Pillager
    - Piglin
    - Shulker
    - Silverfish
    - Stray
    - Vindicator
    - Witch
    - Wither_Skeleton
    - Zoglin
    - Zombie_villager
    Worlds:
    - Survival_world
    - Survival_world_nether
    - Survival_world_the_end
    - Server_dungeon
  Iron_golem&Snowman:
    RemoveExisting: true
    Use: true
    Limit: 10
    List:
    - Iron_golem
    - Snowman
    Worlds:
    - Survival_world
    - Survival_world_nether
    - Survival_world_the_end
    - Server_dungeon
  Villager:
    RemoveExisting: true
    Use: true
    Limit: 10
    List:
    - Villager
    Worlds:
    - Survival_world
    - Survival_world_nether
    - Survival_world_the_end
    - Server_dungeon
  Minecart:
    RemoveExisting: true
    Use: true
    Limit: 10
    List:
    - Minecart
    - Minecart_furnace
    - Minecart_tnt
    - Minecart_hopper
    - Minecart_chest
    Worlds:
    - Survival_world
    - Survival_world_nether
    - Survival_world_the_end
    - Server_dungeon
  Boat:
    RemoveExisting: true
    Use: true
    Limit: 10
    List:
    - Boat
    - Chest_boat
    Worlds:
    - Survival_world
    - Survival_world_nether
    - Survival_world_the_end
    - Server_dungeon
  Dropped_item:
    RemoveExisting: true
    Use: true
    Limit: 300
    List:
    - Dropped_item
    Worlds:
    - Survival_world
    - Survival_world_nether
    - Survival_world_the_end
    - Server_dungeon
  Fish:
    RemoveExisting: true
    Use: true
    Limit: 10
    List:
    - Cod
    - Salmon
    - Tropical_fish
    - Pufferfish
    Worlds:
    - Survival_world
    - Survival_world_nether
    - Survival_world_the_end
    - Server_dungeon
  Squid:
    RemoveExisting: true
    Use: true
    Limit: 10
    List:
    - Squid
    - Glow_squid
    Worlds:
    - Survival_world
    - Survival_world_nether
    - Survival_world_the_end
    - Server_dungeon
  Bat:
    RemoveExisting: true
    Use: true
    Limit: 10
    List:
    - Bat
    Worlds:
    - Survival_world
    - Survival_world_nether
    - Survival_world_the_end
    - Server_dungeon
  Dolphin:
    RemoveExisting: true
    Use: true
    Limit: 10
    List:
    - Dolphin
    Worlds:
    - Survival_world
    - Survival_world_nether
    - Survival_world_the_end
    - Server_dungeon
  Wither:
    RemoveExisting: true
    Use: true
    Limit: 10
    List:
    - Wither
    Worlds:
    - Survival_world
    - Survival_world_nether
    - Survival_world_the_end
    - Server_dungeon
  Warden:
    RemoveExisting: true
    Use: true
    Limit: 10
    List:
    - Warden
    Worlds:
    - Survival_world
    - Survival_world_nether
    - Survival_world_the_end
    - Server_dungeon
  Wither_Skull:
    RemoveExisting: true
    Use: true
    Limit: 10
    List:
    - Wither_skull
    Worlds:
    - Survival_world
    - Survival_world_nether
    - Survival_world_the_end
    - Server_dungeon
  Phantom:
    RemoveExisting: true
    Use: true
    Limit: 10
    List:
    - Phantom
    Worlds:
    - Survival_world
    - Survival_world_nether
    - Survival_world_the_end
    - Server_dungeon
```
