### ISSUE TITLE
Dropped items cannot be removed

### ISSUE THREAD

**Issue by siulung201314** [Zrips/MobFarmManager#95]
Purpur version: 1.21.1
Mobfarmmanger version: 3.0.2.4
CMILib version: 1.5.2.5

I have set
```
  Dropped_item:
    RemoveExisting: true
    Use: true
    Limit: 300
    List:
    - Dropped_item
    Worlds:
    - world
    - world_nether
    - world_the_end
```

However, the dropped items are not removed when there are more than 300 dropped items.
