### ISSUE TITLE
the related config about world does not work properly

### ISSUE THREAD

**Issue by siulung201314** [Zrips/MobFarmManager#96]
Purpur version: 1.21.1
Mobfarmmanger version: 3.0.2.4
CMILib version: 1.5.2.5

In the part of ignored worlds' list,
There is "Christmas" in it.
However, the mobs are still removed in the world called Christmas.

In the part of EntityGroups,
There is no "Chirstmas" is the world list.
However, the mobs are still removed in the world called Christmas.

It seems that the related config about world does not work properly.

**Comment by siulung201314** [comment]
Any news?

I provide related part from the config.

```
Ignore:
  #  
  # When this set to true, armor stands with items on it will be ignored on chunk cleanup
  # Recomended to keep it at true to avoid player item deletion
  FullArmorStands: true
  #  
  # When this set to true, entities which picked items, will be ignored on chunk cleanup
  # Recommended to keep it at true to avoid player item deletion
  EntityWithPickedItem: false
  #  
  # When this set to true, item frames with items in it will be ignored on chunk cleanup
  # Recomended to keep it at true to avoid player item deletion
  FullItemFrames: true
  #  
  # When this set to true, tamed animals will be ignored
  # Recomended to keep it at true to avoid player animals being despawned
  TamedAnimals: false
  #  
  # When this set to true, animals with custom name will be ignored
  # Recomended to keep it at true to avoid special player animals being despawned
  NamedAnimals: false
  #  
  # When this set to true, animals with sadle will be ignored
  # Recomended to keep it at true to avoid special player animals being despawned
  WithSadle: false
  #  
  # When this set to true, baby animals will be ignored
  BabyAnimals: false
  #  
  # List of worlds to be ignored by plugin
  Worlds:
  - Christmas

EntityGroups:
  Iron_golem:
    RemoveExisting: true
    Use: true
    Limit: 10
    List:
    - Iron_golem
    Worlds:
    - world
    - world_nether
    - world_the_end
```

I have a world called "Christmas".
"Christmas" is in the list of worlds to be ignored by plugin.
And "Christmas" is not in the list of worlds in Entity Groups.
However, Iron golem is still removed if there are too many iron golems in a chunk.
